import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#4d8eff",
        "inverse-on-surface": "#2e3038",
        "outline-variant": "#424754",
        "on-tertiary": "#402d00",
        "background": "#050508",
        "secondary": "#ddb7ff",
        "inverse-surface": "#e1e2ec",
        "surface-tint": "#adc6ff",
        "on-error": "#690005",
        "surface": "#0a0a0f",
        "tertiary-container": "#b88900",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffdf9f",
        "on-tertiary-fixed-variant": "#5c4300",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#261a00",
        "on-primary": "#002e6a",
        "on-surface": "#e1e2ec",
        "surface-dim": "#10131a",
        "surface-container-low": "#13141a",
        "surface-container": "#181a20",
        "secondary-fixed": "#f0dbff",
        "tertiary": "#f9bd22",
        "inverse-primary": "#005ac2",
        "on-primary-container": "#00285d",
        "on-error-container": "#ffdad6",
        "on-background": "#e1e2ec",
        "surface-container-high": "#1e2028",
        "surface-bright": "#2a2d36",
        "secondary-fixed-dim": "#ddb7ff",
        "outline": "#8c909f",
        "on-tertiary-container": "#372700",
        "surface-variant": "#1c1e26",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary-fixed": "#2c0051",
        "secondary-container": "#6f00be",
        "on-primary-fixed-variant": "#004395",
        "surface-container-lowest": "#050508",
        "surface-container-highest": "#242730",
        "tertiary-fixed-dim": "#f9bd22",
        "on-secondary": "#490080",
        "primary": "#adc6ff",
        "on-surface-variant": "#a0a4b8",
        "on-secondary-container": "#d6a9ff",
        "error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        // legacy colors
        "legacy-primary": "#39FF14",
        "legacy-secondary": "#D1FFBD",
        "background-light": "#FFFFFF",
          "background-dark": "#000000",
          "surface-dark": "#0A0A0A",
          "black-100": "#100d25",
          "black-200": "#090325",
        "white-100": "#f3f3f3",
        "ink-black": "#1a1a1a",
        "paper-gray": "#d3d3d3",
        "dark-paper": "#a8a8a8",
        "highlighter-blue": "#0000ff",
        "sharpie-blue": "#0022cc",
        "tape-clear": "rgba(255, 255, 255, 0.25)",
        // Dark mode overrides
        "dark-bg": "#0a0a0a",
        "dark-surface": "#141414",
        "dark-border": "#2a2a2a",
        "dark-text": "#e0e0e0",
        // Cyber theme
        "cyber-bg": "#0d0221",
        "cyber-accent": "#00ff9f",
        "cyber-secondary": "#ff00ff",
        "cyber-surface": "#190535",
      },
      fontFamily: {
        "headline-md": ["Georgia", "Times New Roman", "serif"],
        "code": ["Consolas", "SFMono-Regular", "Menlo", "monospace"],
        "body-lg": ["Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        "headline-xl": ["Georgia", "Times New Roman", "serif"],
        "body-md": ["Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        "headline-lg": ["Georgia", "Times New Roman", "serif"],
        "caption": ["Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        brand: ["Impact", "Haettenschweiler", "Arial Narrow Bold", "sans-serif"],
        ransom: ["Impact", "Haettenschweiler", "Arial Narrow Bold", "sans-serif"],
        display: ["Impact", "Haettenschweiler", "Arial Narrow Bold", "sans-serif"],
        marker: ["Brush Script MT", "Segoe Script", "cursive"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        body: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        sans: ["system-ui", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "300" }],
        "code": ["13px", { lineHeight: "1.5", letterSpacing: "0px", fontWeight: "300" }],
        "body-lg": ["18px", { lineHeight: "1.7", letterSpacing: "0px", fontWeight: "300" }],
        "headline-xl": ["88px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "300" }],
        "body-md": ["15px", { lineHeight: "1.7", letterSpacing: "0px", fontWeight: "300" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "300" }],
        "caption": ["12px", { lineHeight: "1.4", letterSpacing: "0.04em", fontWeight: "400" }]
      },
      boxShadow: {
        card: "0px 35px 120px -15px #211e35",
        brutalist: "6px 6px 0px 0px #39FF14",
        cutout: "3px 3px 0px 0px rgba(0,0,0,1)",
        "cutout-hover": "6px 6px 0px 0px rgba(0,0,0,1)",
        staple: "1px 1px 1px rgba(0,0,0,0.5)",
        'glass-inner': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.1)',
        'glow': '0 0 40px -10px rgba(77, 142, 255, 0.3)',
      },
      screens: {
        xs: "450px",
      },
      backgroundImage: {
        "paper-texture":
          "url('https://www.transparenttextures.com/patterns/concrete-wall.png')",
        halftone: "radial-gradient(circle, #000 2px, transparent 2.5px)",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        }
      },
      animation: {
        marquee: "marquee 20s linear infinite",
        blob: 'blob 20s infinite',
      },
    },
  },
  plugins: [],
};

export default config;
